### PR TITLE
new Video uploaded

### PR DESCRIPTION
**Pull request by vutukuriajay2241**
New video uploaded

### CODE REVIEW

**Comment by vutukuriajay2241** [comment]
I think instead of youtube player uploading is good because it shows all the suggestions and other stuff.

**Comment by bherr2** [comment]
> I think instead of youtube player uploading is good because it shows all the suggestions and other stuff.

In the CCF RUI and EUI we use youtube player for demos. If they show those suggestions let me know and @andreasbueckle can turn them off.

**Comment by vutukuriajay2241** [comment]
I will try to implement that.

**Comment by vutukuriajay2241** [comment]
Will let you know if I have any troubles

**Comment by andreasbueckle** [comment]
Note that I'll be ooo between June 20 and August 2. Here is a link to the raw MP4 in case you need it:
https://drive.google.com/file/d/1HFPVptjlCakU7bSJxJGXrNCjIEzOTRZ0/view?usp=sharing

**Comment by macvogelsang** [comment]
@bherr2 @andreasbueckle Implemented the Youtube Embedding, but as expected, it is showing related videos at the bottoms. [As of August 2018](https://developers.google.com/youtube/player_parameters.html?playerVersion=HTML5#august-23,-2018), the Youtube API no longer supports disabling this banner entirely.

**Review by bherr2 — APPROVED** [review]

**Pull request merged**
