### PR TITLE
Angular 17 upgrade

### PR DESCRIPTION
**Pull request by edlu77**

### CODE REVIEW

**Comment by bherr2** [comment]
What is the alternative to mat table exporter?

**Comment by bherr2** [comment]
Looks like maybe it doesn't use it actually. Please verify, but otherwise the build preview looks to be working.

**Comment by edlu77** [comment]
> Looks like maybe it doesn't use it actually. Please verify, but otherwise the build preview looks to be working.

It looks to be redundant, think it's safe to just get rid of it.

**Comment by bherr2** [comment]
Please fix tests

**Comment by bherr2** [comment]
Done in hra-ui repo

**Pull request closed without merging**
